apiVersion: v1
kind: Template
metadata:
  name: http-endpoints
  annotations:
    openshift.io/display-name: "HTTP Endpoints"
    description: |-
      HTTP/S endpoints
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: httpendpoints
  spec:
    dockerImageRepository: syndesisqe/httpendpoints
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: httpendpoints
    name: httpendpoints
  spec:
    replicas: 1
    selector:
      app: httpendpoints
    template:
      metadata:
        labels:
          app: httpendpoints
      spec:
        containers:
        - name: http-endpoints
          image: ' '
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - http-endpoints
        from:
          kind: ImageStreamTag
          name: httpendpoints:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: http-svc
    labels:
      app: httpendpoints
  spec:
    ports:
    - port: 8080
      name: http-port
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: httpendpoints

- apiVersion: v1
  kind: Service
  metadata:
    name: https-svc
    labels:
      app: httpendpoints
  spec:
    ports:
    - port: 8443
      name: https-port
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: httpendpoints
